apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-express
spec:
  selector:
    matchLabels:
      app: web-express
  replicas: 1
  template:
    metadata:
      labels:
        app: web-express
    spec:
      containers:
      - name: web-express
        image: minhlkz/simple-nodejs-express:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web-express-service
spec:
  type: NodePort
  selector:
    app: web-express
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
